// <auto-generated />
namespace ReferEngine.Common.iOSMigrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class LongDownloadSize : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LongDownloadSize));
        
        string IMigrationMetadata.Id
        {
            get { return "201305191816047_LongDownloadSize"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
