// <auto-generated />
namespace ReferEngine.Common.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AppScreenshots : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AppScreenshots));
        
        string IMigrationMetadata.Id
        {
            get { return "201304271950065_AppScreenshots"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
