// <auto-generated />
namespace ReferEngine.Common.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Cloudinary4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cloudinary4));
        
        string IMigrationMetadata.Id
        {
            get { return "201304052041008_Cloudinary4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
