// <auto-generated />
namespace ReferEngine.Common.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CloudinaryHash : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CloudinaryHash));
        
        string IMigrationMetadata.Id
        {
            get { return "201306052151174_CloudinaryHash"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
