// <auto-generated />

using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace AppSmarts.Common.Migrations
{
    public sealed partial class AppLogoLinks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AppLogoLinks));
        
        string IMigrationMetadata.Id
        {
            get { return "201212282027508_AppLogoLinks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
