// <auto-generated />

using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace AppSmarts.Common.Migrations
{
    public sealed partial class AppCloudinaryImages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AppCloudinaryImages));
        
        string IMigrationMetadata.Id
        {
            get { return "201304052216533_AppCloudinaryImages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
