// <auto-generated />

using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace AppSmarts.Common.Migrations
{
    public sealed partial class Cloudinary2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cloudinary2));
        
        string IMigrationMetadata.Id
        {
            get { return "201304052029341_Cloudinary2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
