// <auto-generated />

using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace AppSmarts.Common.Migrations
{
    public sealed partial class Cloudinary3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cloudinary3));
        
        string IMigrationMetadata.Id
        {
            get { return "201304052033371_Cloudinary3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
