// <auto-generated />

using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace AppSmarts.Common.Migrations
{
    public sealed partial class CollectionOfImages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CollectionOfImages));
        
        string IMigrationMetadata.Id
        {
            get { return "201304052020082_CollectionOfImages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
