// <auto-generated />

using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace AppSmarts.Common.Migrations
{
    public sealed partial class Categories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Categories));
        
        string IMigrationMetadata.Id
        {
            get { return "201304062017485_Categories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
