// <auto-generated />

using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace AppSmarts.Common.Migrations
{
    public sealed partial class AddIpAddressToView : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddIpAddressToView));
        
        string IMigrationMetadata.Id
        {
            get { return "201303012018017_AddIpAddressToView"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
