// <auto-generated />

using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace AppSmarts.Common.iOSMigrations
{
    public sealed partial class NotSureWhatChanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NotSureWhatChanged));
        
        string IMigrationMetadata.Id
        {
            get { return "201305222302178_NotSureWhatChanged"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
