// <auto-generated />

using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace AppSmarts.Common.iOSMigrations
{
    public sealed partial class DataImportStep : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DataImportStep));
        
        string IMigrationMetadata.Id
        {
            get { return "201305250008389_DataImportStep"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
